#server:
#  port: 9005

#spring:
#  application:
#    name: config-server
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/BobLi-love/springcloud_demo/
#          search-paths: /config-demo/
#          username: BobLi-love
#          password:
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8080/eureka

server:
  port: 9005

spring:
  application:
    name: config-server
  profiles:
    active: native
  # 配置中心
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

# 注册中心配置
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
#
## 暴露监控端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'