server:
  port: 8080
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
  server:
    eviction-interval-timer-in-ms: 30000
#    enable-self-preservation: true
