server:
  port: 9005

spring:
  application:
    name: config-server
  cloud:
    config.server:
      git:
        uri: https://github.com/xuwujing/springcloud-study/
        search-paths: /springcloud-config/config-repo
        username:
        password:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka